package gregsjourney.loaders.recipe;

public final class GJRecipeLoader {

    private GJRecipeLoader() {}

    public static void init() {
        RecipeRemoval.init();
        //GasGasGas.init();
        AutogeneratedRecipes.init();
        // ForestryModule.registerRecipes();
        // ThaumcraftModule.registerRecipes();
    }
}
