package thegreggening.common.recipe;

public final class TGRecipeLoader {

    private TGRecipeLoader() {}

    public static void init() {
        RecipeRemoval.init();
        AutogeneratedRecipes.init();
    }
}
