package gregsjourney.api.unification.property;

import gregtech.api.unification.material.info.MaterialFlag;

public class GJMaterialFlags {
    public static final MaterialFlag CRYSTALLIZABLE = new MaterialFlag.Builder("crystallizable").build();
    public static final MaterialFlag DISTILLABLE = new MaterialFlag.Builder("distillable").build();
    public static final MaterialFlag SOLVENT = new MaterialFlag.Builder("solvent").build();
    public static final MaterialFlag ORE_LEACH = new MaterialFlag.Builder("ore_leach").build();
    public static final MaterialFlag ORE_SLAG = new MaterialFlag.Builder("ore_slag").build();
    public static final MaterialFlag ROASTED_ORE = new MaterialFlag.Builder("roasted_ore").build();
    public static final MaterialFlag AUTOGENERATED_SOLUTION_MIXING_RECIPE = new MaterialFlag.Builder("autogenerated_solution_mixing_recipe").build();
    public static final MaterialFlag AUTOGENERATED_ORE_TAILING_RECIPE = new MaterialFlag.Builder("autogenerated_ore_tailing_recipe").build();
    public static final MaterialFlag FISSIONABLE = new MaterialFlag.Builder("fissionable").build();
    public static final MaterialFlag GENERATE_NUCLEAR_FUELS = new MaterialFlag.Builder("generate_nuclear_fuels").build();
}
